SELECT CART_ID
FROM CART_PRODUCTS
WHERE CART_ID IN (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME  LIKE 'MILK'
    ) AND NAME LIKE 'Yogurt'
ORDER BY CART_ID

# 아래는 한번에 구하는 방법 

# SELECT CART_ID
# FROM CART_PRODUCTS
# WHERE NAME IN ('Milk', 'Yogurt')
# GROUP BY CART_ID
# HAVING COUNT(DISTINCT NAME) = 2
# ORDER BY CART_ID