-- 코드를 입력하세요
SELECT product_code, SUM(P.PRICE * O.SALES_AMOUNT) as SALES
FROM PRODUCT AS P
INNER JOIN OFFLINE_SALE AS O ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY product_code
ORDER BY SALES DESC, product_code