SELECT DATE_FORMAT(SALES_DATE,"%Y-%m-%d") AS SALES_DATE,
    PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE LIKE '2022-03-%'

UNION

SELECT DATE_FORMAT(SALES_DATE,"%Y-%m-%d") AS SALES_DATE, 
    PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE LIKE '2022-03-%'

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID

# UNION 할떄는 첫번째 SELECT 문에서 정한 칼럼이름과 개수가 기준이됨
# NULL AS USER_ID -> NULL 값으로 채우기 