SELECT YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    U.GENDER,
    count(DISTINCT U.USER_ID) AS USERS
FROM USER_INFO AS U 
INNER JOIN ONLINE_SALE AS S ON U.USER_ID = S.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, U.GENDER
ORDER BY YEAR, MONTH, GENDER