SELECT P.PRODUCT_ID, 
       P.PRODUCT_NAME, 
       SUM(PRICE * AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS P 
INNER JOIN FOOD_ORDER AS O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY TOTAL_SALES  DESC, P.PRODUCT_ID

# 총 매출 이라는 단어가 나오면 SUM, GROUP BY 세트가 필요함