SELECT FLAVOR
FROM (
    SELECT FLAVOR, 	TOTAL_ORDER FROM FIRST_HALF
    UNION ALL
    SELECT FLAVOR, 	TOTAL_ORDER FROM JULY
) AS TOTAL_ICE_CREAM
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC 
LIMIT 3