-- 코드를 입력하세요
SELECT DISTINCT C.car_id 
FROM CAR_RENTAL_COMPANY_CAR as C
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY as R ON C.CAR_ID = R.CAR_ID
WHERE car_type = '세단' AND MONTH(START_DATE) = 10
ORDER BY C.car_id DESC
